include:
- project: 'quantum-research/tensornetworksimulation/rust-ci'
  ref: a0be555a70806225648e79edfb5ba7a5ee2deccb
  file: 'template.yml'

variables:
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
