include:
- project: 'quantum-research/tensornetworksimulation/rust-ci'
  ref: 1c1ba34a1d42bf5230fa63b4fd99a44773015415
  file: 'template.yml'

variables:
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
