[package]
name = "tensorcontraction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool = "1.0.3"
criterion = "0.4.0"
hdf5 = { version = "0.8.1", features = [
    "complex",
], git = "https://github.com/keefehuang/hdf5-rust.git", branch = "feature/complex" }
itertools = "0.10.5"
linked_hash_set = "0.1.4"
log = "0.4.17"
num-complex = "0.4.2"
rand = "0.8.5"
random = "0.13.2"
antlr-rust = "0.3.0-beta"
float-cmp = "0.9.0"
tetra = { git = "ssh://gitlab.lrz.de/quantum-research/tetra", version = "0.1.0" }

[dev-dependencies]
tux = "0.2.2"

[[bench]]
name = "benchmarks"
harness = false

[dev-dependencies]
float-cmp = "0.9.0"
