[package]
name = "tensorcontraction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool = "1.0.3"
itertools = "0.10.5"
linked_hash_set = "0.1.4"
log = "0.4.17"
num-complex = "0.4.2"
rand = "0.8.5"
random = "0.13.2"
taco-sys = { git = "ssh://gitlab.lrz.de/quantum-research/taco-sys.git", tag = "v0.5.0", version = "0.5.0" }
antlr-rust = "0.3.0-beta"

[dev-dependencies]
tux = "0.2.2"
