[package]
name = "tensorcontraction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpi = { version = "0.8.0", features = ["complex", "derive"] }
array_tool = "1.0.3"
criterion = "0.5.1"
hdf5 = { git = "https://github.com/aldanor/hdf5-rust.git", features = ["complex"] }
itertools = "0.13.0"
linked_hash_set = "0.1.4"
log = "0.4.21"
num-complex = "0.4.2"
rand = "0.8.5"
random = "0.14.0"
antlr-rust = "0.3.0-beta"
float-cmp = "0.9.0"
tetra = { git = "ssh://gitlab.lrz.de/quantum-research/tetra", branch = "main", features = ["serde"] }
kahypar-sys = { git = "ssh://gitlab.lrz.de/quantum-research/kahypar-sys", branch = "main" }
permutation = "0.4.1"
memoffset = "0.9.1"
serde = "1.0.203"
bincode = "1.3.3"

[dev-dependencies]
mpi_test = { git = "ssh://gitlab.lrz.de/quantum-research/mpi_test", branch = "main" }
ndarray = "0.15.6"
tux = "0.2.2"

[[bench]]
name = "benchmarks"
harness = false
