[package]
name = "tensorcontraction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool = "1.0.3"
linked_hash_set = "0.1.4"
log = "0.4.17"
rand = "0.8.5"
